service: aws-python-http-api
frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: "20201221"

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
    zip: true

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
